apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalwebsite
  labels:
    app: mywebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: finalwebsite
          image: prodimage
          ports:
            - containerPort: 80